- id: ae000001-0000-4000-a000-000000000001
  name: Damage
  dealsDamage: true
  statusName: null
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000002
  name: Stun
  dealsDamage: false
  statusName: stunned
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000003
  name: Buff Attack
  dealsDamage: false
  statusName: berserk
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000004
  name: Buff Defense
  dealsDamage: false
  statusName: shielded
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000005
  name: Evasion
  dealsDamage: false
  statusName: phased
  overrideTargetsHit: 0

- id: ae000001-0000-4000-a000-000000000006
  name: Resurrect
  dealsDamage: false
  statusName: resurrected
  overrideTargetsHit: 1

# --- Invader ability effects ---

- id: ae000001-0000-4000-a000-000000000007
  name: Heal
  dealsDamage: false
  statusName: healing
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000008
  name: Disarm
  dealsDamage: false
  statusName: disarm
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000009
  name: Magic Damage
  dealsDamage: true
  statusName: null
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000010
  name: Dispel
  dealsDamage: false
  statusName: dispel
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000011
  name: Fear Immunity
  dealsDamage: false
  statusName: courage
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000012
  name: Scout
  dealsDamage: false
  statusName: scouting
  overrideTargetsHit: null

- id: ae000001-0000-4000-a000-000000000013
  name: Mark
  dealsDamage: false
  statusName: marked
  overrideTargetsHit: null
