- id: a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d
  name: Goblin Trapper
  description: A cunning hybrid combining goblin tenacity with kobold agility. Excels at swift ambushes and trap-setting.
  parentInhabitantAId: Goblin
  parentInhabitantBId: Kobold
  resultName: Goblin Trapper
  statBonuses:
    speed: 3
    attack: 2
  timeMultiplier: 1.0

- id: b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e
  name: Skeletal Goblin
  description: An undead goblin reanimated with reinforced bones. Tougher than either parent, but sluggish.
  parentInhabitantAId: Goblin
  parentInhabitantBId: Skeleton
  resultName: Skeletal Goblin
  statBonuses:
    hp: 5
    defense: 3
  timeMultiplier: 1.2

- id: c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f
  name: Fungal Revenant
  description: A mushroom-infused skeleton sustained by symbiotic spores. Regenerates slowly and works with eerie efficiency.
  parentInhabitantAId: Skeleton
  parentInhabitantBId: Myconid
  resultName: Fungal Revenant
  statBonuses:
    hp: 4
    workerEfficiency: 0.3
  timeMultiplier: 1.5

- id: d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80
  name: Spore Stalker
  description: A kobold mutated by myconid spores, gaining fungal camouflage and enhanced work capacity.
  parentInhabitantAId: Kobold
  parentInhabitantBId: Myconid
  resultName: Spore Stalker
  statBonuses:
    speed: 2
    workerEfficiency: 0.2
  timeMultiplier: 1.0

- id: e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091
  name: Acidic Runt
  description: A slime-goblin hybrid that oozes corrosive mucus. Small but surprisingly aggressive.
  parentInhabitantAId: Slime
  parentInhabitantBId: Goblin
  resultName: Acidic Runt
  statBonuses:
    attack: 3
    speed: 2
  timeMultiplier: 0.8

- id: be36b6cc-3e59-4d3b-8792-9fc74db170c1
  name: Treant Guardian
  description: A massive living tree animated by dryad magic and reinforced with gargoyle stone. An immovable forest sentinel.
  parentInhabitantAId: Dryad
  parentInhabitantBId: Gargoyle
  resultName: Treant Guardian
  statBonuses:
    hp: 10
    defense: 8
  timeMultiplier: 1.5

- id: 15dc4bba-9220-45cf-aeba-bdccc0eaef74
  name: Thornweaver
  description: A vine-covered dryad hybrid with myconid spores woven into its bark. Excels at food production and regeneration.
  parentInhabitantAId: Dryad
  parentInhabitantBId: Myconid
  resultName: Thornweaver
  statBonuses:
    hp: 3
    workerEfficiency: 0.3
  timeMultiplier: 1.2

- id: 03bc936c-d8fc-4165-9a51-122c13e0ef75
  name: Obsidian Sentinel
  description: A gargoyle fused with skeletal reinforcement. Harder than stone and twice as relentless.
  parentInhabitantAId: Gargoyle
  parentInhabitantBId: Skeleton
  resultName: Obsidian Sentinel
  statBonuses:
    defense: 6
    hp: 8
  timeMultiplier: 1.5

- id: 7beba29b-966a-4d80-b79c-f9529379f91c
  name: Stone Imp
  description: An imp encased in stone armor. Retains its fiery temperament but gains surprising durability.
  parentInhabitantAId: Imp
  parentInhabitantBId: Gargoyle
  resultName: Stone Imp
  statBonuses:
    defense: 5
    attack: 3
  timeMultiplier: 1.3

- id: 7691e428-a9dd-4da3-8848-1185a645d1d3
  name: Hellfire Sprite
  description: A volatile fusion of imp cunning and goblin tenacity. Fast, chaotic, and wreathed in flame.
  parentInhabitantAId: Imp
  parentInhabitantBId: Goblin
  resultName: Hellfire Sprite
  statBonuses:
    speed: 4
    attack: 3
  timeMultiplier: 0.8

- id: 91d80a98-f916-44bf-b298-b698e8cf2bff
  name: Blighted Dryad
  description: A dryad corrupted by imp fire. Its nature magic is twisted but devastatingly powerful.
  parentInhabitantAId: Dryad
  parentInhabitantBId: Imp
  resultName: Blighted Dryad
  statBonuses:
    attack: 5
    workerEfficiency: 0.2
  timeMultiplier: 1.4

- id: eeb601b9-061a-44e8-8b04-ebc34e469ca3
  name: War Goblin
  description: A goblin trained and bred alongside orcs, combining orcish brawn with goblin cunning. A fierce raider.
  parentInhabitantAId: Orc
  parentInhabitantBId: Goblin
  resultName: War Goblin
  statBonuses:
    attack: 4
    speed: 3
  timeMultiplier: 1.0

- id: 95ebd98c-5aa4-402c-8b12-aa86a36af1e8
  name: Bone Crusher
  description: An orc fused with skeletal reinforcement. Tireless, brutal, and nearly unbreakable on the front lines.
  parentInhabitantAId: Orc
  parentInhabitantBId: Skeleton
  resultName: Bone Crusher
  statBonuses:
    hp: 8
    defense: 5
  timeMultiplier: 1.3

- id: 829e3fb7-6741-4119-9cff-e9fbed367095
  name: Phantom Scholar
  description: A wraith fused with an arcane familiar, creating a spectral entity of unmatched intellect. Excels at research above all else.
  parentInhabitantAId: Wraith
  parentInhabitantBId: Arcane Familiar
  resultName: Phantom Scholar
  statBonuses:
    speed: 3
    workerEfficiency: 0.4
  timeMultiplier: 1.2

- id: 02690383-fd24-40df-83ee-e015120ce864
  name: Banshee
  description: A wraith merged with a frost wraith, amplifying its spectral horror into a wailing terror that freezes the blood of invaders.
  parentInhabitantAId: Wraith
  parentInhabitantBId: Frost Wraith
  resultName: Banshee
  statBonuses:
    attack: 4
    hp: 5
  timeMultiplier: 1.4

- id: 0362eaf7-2a66-4e31-af47-69dfdf3c0480
  name: Magma Golem
  description: A Stone Elemental fused with Fire Elemental energy. Molten veins pulse through its rocky frame, making it a devastating combatant and forge worker.
  parentInhabitantAId: Stone Elemental
  parentInhabitantBId: Fire Elemental
  resultName: Magma Golem
  statBonuses:
    attack: 6
    hp: 10
  timeMultiplier: 1.5

- id: 1ce5a488-7f0c-4bb9-b073-0d951da1e8d0
  name: Living Statue
  description: A Stone Elemental animated by gargoyle cunning. Faster and more aware than a pure elemental, yet retains its unyielding durability.
  parentInhabitantAId: Stone Elemental
  parentInhabitantBId: Gargoyle
  resultName: Living Statue
  statBonuses:
    defense: 8
    speed: 4
  timeMultiplier: 1.3

- id: 5f723044-e898-4893-99e2-37dc25c4bedd
  name: Trapjaw
  description: A Mimic crossbred with Kobold ingenuity. Its jaw-like maw snaps shut with mechanical precision, combining shapeshifting ambush tactics with expert trap-craft.
  parentInhabitantAId: Mimic
  parentInhabitantBId: Kobold
  resultName: Trapjaw
  statBonuses:
    attack: 6
    speed: 4
  timeMultiplier: 1.4

- id: 7d924689-7e19-4e93-b05f-be6fc08b032c
  name: Doppelganger
  description: A Mimic merged with Slime adaptability. This amorphous shapeshifter can perfectly replicate any creature it observes, making it the ultimate infiltrator.
  parentInhabitantAId: Mimic
  parentInhabitantBId: Slime
  resultName: Doppelganger
  statBonuses:
    hp: 8
    defense: 4
  timeMultiplier: 1.3

- id: 56b542b8-8c97-4cd7-b097-4cf38db3531c
  name: Death Knight Breeding
  description: A Lich's dark magic fused with orcish ferocity. This undead warlord commands the battlefield with brutal arcane strikes and an aura that empowers fallen warriors.
  parentInhabitantAId: Lich
  parentInhabitantBId: Orc
  resultName: Death Knight
  statBonuses:
    attack: 8
    hp: 12
  timeMultiplier: 1.8

- id: 6f15530b-9e6c-4f7f-8957-7ac792f429b6
  name: Bone Colossus
  description: A Lich's necromantic power merged with a Stone Elemental's mineral frame. This towering construct of enchanted bone and living rock is nearly indestructible.
  parentInhabitantAId: Lich
  parentInhabitantBId: Stone Elemental
  resultName: Bone Colossus
  statBonuses:
    defense: 10
    hp: 15
  timeMultiplier: 2.0
