- id: aa100001-0001-0001-0001-000000000001
  name: Throne Room
  description: The seat of power in your dungeon. Houses a single powerful ruler creature that provides dungeon-wide bonuses.
  shapeId: 635a07d9-11f9-445c-a626-dacd9fbb16bc
  cost:
    gold: 100
    crystals: 50
  production: {}
  requiresWorkers: false
  adjacencyBonuses: []
  isUnique: true
  maxInhabitants: 1
  inhabitantRestriction: unique
  fearLevel: variable

- id: aa100001-0001-0001-0001-000000000002
  name: Crystal Mine
  description: An L-shaped excavation that extracts crystals from deep rock veins. Requires workers for full output. Benefits from proximity to other mines, forges, and libraries.
  shapeId: 5634b24d-d5dd-4a8f-9877-4393cdc05ffb
  cost:
    gold: 50
  production:
    crystals: 1.0
  requiresWorkers: true
  maxInhabitants: 2
  fearLevel: 1
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000002
      bonus: 0.1
    - adjacentRoomType: aa100001-0001-0001-0001-000000000006
      bonus: 0.15
    - adjacentRoomType: aa100001-0001-0001-0001-000000000004
      bonus: 0.1
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000001
      name: Deep Vein Extraction
      description: Optimized mining techniques increase crystal yield by 50%.
      cost:
        crystals: 75
      effects:
        - type: productionMultiplier
          value: 1.5
          resource: crystals
    - id: aa200001-0001-0001-0001-000000000002
      name: Expanded Tunnels
      description: Widen the mine shafts to accommodate more workers, increasing capacity from 2 to 4.
      cost:
        crystals: 60
      effects:
        - type: maxInhabitantBonus
          value: 2
    - id: aa200001-0001-0001-0001-000000000003
      name: Crystal Resonance
      description: Harmonic crystal formations reduce fear in the mine and produce a small amount of flux.
      cost:
        crystals: 80
      effects:
        - type: fearReduction
          value: 1
        - type: secondaryProduction
          value: 0.2
          resource: flux

- id: aa100001-0001-0001-0001-000000000003
  name: Mushroom Grove
  description: A T-shaped grove of bioluminescent fungi that feeds your dungeon inhabitants. Thrives near water and darkness. Requires workers for full output.
  shapeId: 0279e677-6073-4a18-b57b-8e6008f4a3a5
  cost:
    gold: 40
  production:
    food: 1.6
  requiresWorkers: true
  maxInhabitants: 3
  fearLevel: 1
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000005
      bonus: 0.4
    - adjacentRoomType: aa100001-0001-0001-0001-000000000004
      bonus: 0.15
    - adjacentRoomType: aa100001-0001-0001-0001-000000000006
      bonus: 0.15
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000004
      name: Bountiful Harvest
      description: Enhanced fungal cultivation techniques increase food yield by 50%.
      cost:
        gold: 60
      effects:
        - type: productionMultiplier
          value: 1.5
          resource: food
    - id: aa200001-0001-0001-0001-000000000005
      name: Expanded Growth
      description: Extend the growing chambers to accommodate more workers, increasing capacity from 3 to 5.
      cost:
        gold: 50
      effects:
        - type: maxInhabitantBonus
          value: 2
    - id: aa200001-0001-0001-0001-000000000006
      name: Tranquil Garden
      description: Calming spores and gentle bioluminescence eliminate all fear in the grove.
      cost:
        gold: 45
      effects:
        - type: fearReduction
          value: 1

- id: aa100001-0001-0001-0001-000000000004
  name: Shadow Library
  description: A repository of forbidden knowledge. Generates research points passively.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost:
    gold: 80
    crystals: 30
  production:
    research: 0.8
  requiresWorkers: true
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000005
  name: Soul Well
  description: Draws essence from the spiritual plane. Produces essence passively.
  shapeId: aa000000-0000-0000-0000-000000000001
  cost:
    gold: 100
    crystals: 50
  production:
    essence: 0.3
  requiresWorkers: false
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000006
  name: Dark Forge
  description: Smelts ores and crafts equipment. Produces gold when worked.
  shapeId: aa000000-0000-0000-0000-000000000003
  cost:
    gold: 60
    crystals: 20
  production:
    gold: 1.2
  requiresWorkers: true
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000002
      bonus: 0.15

- id: aa100001-0001-0001-0001-000000000007
  name: Barracks
  description: Houses and trains your fighters. No resource production.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost:
    gold: 70
  production: {}
  requiresWorkers: false
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000008
  name: Treasure Vault
  description: A secure chamber for storing gold and valuables. Produces gold passively and boosts the Throne Room when adjacent.
  shapeId: 60e19fcd-7572-4bf0-a626-415be05f6a03
  cost:
    gold: 120
    crystals: 40
  production:
    gold: 0.8
  requiresWorkers: false
  adjacencyBonuses: []
