- id: aa100001-0001-0001-0001-000000000001
  name: Throne Room
  description: The heart of your dungeon. Generates a small amount of gold passively.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost: {}
  production:
    gold: 0.5
  requiresWorkers: false
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000002
  name: Crystal Mine
  description: Extracts crystals from the surrounding rock. Requires workers for full output.
  shapeId: aa000000-0000-0000-0000-000000000001
  cost:
    gold: 50
  production:
    crystals: 1.0
  requiresWorkers: true
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000006
      bonus: 0.1

- id: aa100001-0001-0001-0001-000000000003
  name: Mushroom Grove
  description: Grows food for your inhabitants in the damp dungeon air. Requires workers.
  shapeId: aa000000-0000-0000-0000-000000000001
  cost:
    gold: 40
  production:
    food: 1.5
  requiresWorkers: true
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000004
  name: Shadow Library
  description: A repository of forbidden knowledge. Generates research points passively.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost:
    gold: 80
    crystals: 30
  production:
    research: 0.8
  requiresWorkers: true
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000005
  name: Soul Well
  description: Draws essence from the spiritual plane. Produces essence passively.
  shapeId: aa000000-0000-0000-0000-000000000001
  cost:
    gold: 100
    crystals: 50
  production:
    essence: 0.3
  requiresWorkers: false
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000006
  name: Dark Forge
  description: Smelts ores and crafts equipment. Produces gold when worked.
  shapeId: aa000000-0000-0000-0000-000000000003
  cost:
    gold: 60
    crystals: 20
  production:
    gold: 1.2
  requiresWorkers: true
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000002
      bonus: 0.15

- id: aa100001-0001-0001-0001-000000000007
  name: Barracks
  description: Houses and trains your fighters. No resource production.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost:
    gold: 70
  production: {}
  requiresWorkers: false
  adjacencyBonuses: []
