- id: aa100001-0001-0001-0001-000000000009
  name: Altar Room
  description: The dark heart of your dungeon. This ancient altar is the source of your power, enabling room construction and creature recruitment. Its calming aura reduces fear in adjacent rooms.
  shapeId: 60e19fcd-7572-4bf0-a626-415be05f6a03
  cost: {}
  production:
    essence: 0.2
  requiresWorkers: false
  adjacencyBonuses: []
  isUnique: true
  removable: false
  autoPlace: true
  maxInhabitants: 0
  inhabitantRestriction: null
  fearLevel: 0
  fearReductionAura: 1
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000007
      name: Empowered Altar
      description: Channel deeper magical energies to expand your dungeon-building capabilities and strengthen the calming aura.
      cost:
        gold: 150
        crystals: 75
        essence: 30
      effects:
        - type: fearReductionAura
          value: 2
        - type: secondaryProduction
          value: 0.2
          resource: essence
    - id: aa200001-0001-0001-0001-000000000008
      name: Ascendant Altar
      description: Unlock the altar's full potential, granting access to advanced rooms and maximizing its stabilizing influence.
      cost:
        gold: 300
        crystals: 150
        essence: 60
      effects:
        - type: fearReductionAura
          value: 3
        - type: secondaryProduction
          value: 0.4
          resource: essence
        - type: secondaryProduction
          value: 0.2
          resource: flux

- id: aa100001-0001-0001-0001-000000000001
  name: Throne Room
  description: The seat of power in your dungeon. Houses a single powerful ruler creature that provides dungeon-wide bonuses.
  shapeId: 635a07d9-11f9-445c-a626-dacd9fbb16bc
  cost:
    gold: 100
    crystals: 50
  production: {}
  requiresWorkers: false
  adjacencyBonuses: []
  isUnique: true
  maxInhabitants: 1
  inhabitantRestriction: unique
  fearLevel: variable

- id: aa100001-0001-0001-0001-000000000002
  name: Crystal Mine
  description: An L-shaped excavation that extracts crystals from deep rock veins. Requires workers for full output. Benefits from proximity to other mines, forges, and libraries.
  shapeId: 5634b24d-d5dd-4a8f-9877-4393cdc05ffb
  cost:
    gold: 50
  production:
    crystals: 1.0
  requiresWorkers: true
  maxInhabitants: 2
  fearLevel: 1
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000002
      bonus: 0.1
      description: Shared mineral veins between adjacent mines boost extraction.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000006
      bonus: 0.15
      description: Nearby forge heats rock, making crystal extraction easier.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000004
      bonus: 0.1
      description: Library scholars identify optimal mining patterns.
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000001
      name: Deep Vein Extraction
      description: Optimized mining techniques increase crystal yield by 50%.
      cost:
        crystals: 75
      effects:
        - type: productionMultiplier
          value: 1.5
          resource: crystals
    - id: aa200001-0001-0001-0001-000000000002
      name: Expanded Tunnels
      description: Widen the mine shafts to accommodate more workers, increasing capacity from 2 to 4.
      cost:
        crystals: 60
      effects:
        - type: maxInhabitantBonus
          value: 2
    - id: aa200001-0001-0001-0001-000000000003
      name: Crystal Resonance
      description: Harmonic crystal formations reduce fear in the mine and produce a small amount of flux.
      cost:
        crystals: 80
      effects:
        - type: fearReduction
          value: 1
        - type: secondaryProduction
          value: 0.2
          resource: flux

- id: aa100001-0001-0001-0001-000000000003
  name: Mushroom Grove
  description: A T-shaped grove of bioluminescent fungi that feeds your dungeon inhabitants. Thrives near water and darkness. Requires workers for full output.
  shapeId: 0279e677-6073-4a18-b57b-8e6008f4a3a5
  cost:
    gold: 40
  production:
    food: 1.6
  requiresWorkers: true
  maxInhabitants: 3
  fearLevel: 1
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000005
      bonus: 0.4
      description: Soul Well moisture accelerates fungal growth dramatically.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000004
      bonus: 0.15
      description: Library knowledge improves cultivation techniques.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000006
      bonus: 0.15
      description: Forge warmth creates ideal growing conditions.
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000004
      name: Bountiful Harvest
      description: Enhanced fungal cultivation techniques increase food yield by 50%.
      cost:
        gold: 60
      effects:
        - type: productionMultiplier
          value: 1.5
          resource: food
    - id: aa200001-0001-0001-0001-000000000005
      name: Expanded Growth
      description: Extend the growing chambers to accommodate more workers, increasing capacity from 3 to 5.
      cost:
        gold: 50
      effects:
        - type: maxInhabitantBonus
          value: 2
    - id: aa200001-0001-0001-0001-000000000006
      name: Tranquil Garden
      description: Calming spores and gentle bioluminescence eliminate all fear in the grove.
      cost:
        gold: 45
      effects:
        - type: fearReduction
          value: 1

- id: aa100001-0001-0001-0001-000000000004
  name: Shadow Library
  description: A repository of forbidden knowledge shrouded in arcane darkness. Scholars study ancient tomes to generate research points. Its eerie atmosphere unsettles all but the most resolute inhabitants.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost:
    gold: 80
    crystals: 30
  production:
    research: 0.6
  requiresWorkers: true
  maxInhabitants: 1
  fearLevel: 2
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000005
      bonus: 0.15
      description: Soul essence enhances arcane research comprehension.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000002
      bonus: 0.1
      description: Crystal mine ore samples provide material for arcane study.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000004
      bonus: 0.2
      description: Adjacent libraries share knowledge and cross-reference tomes.
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000010
      name: Arcane Focus
      description: Enchanted reading lenses and amplified candlelight drastically improve research throughput.
      cost:
        gold: 100
        crystals: 60
        essence: 20
      effects:
        - type: productionMultiplier
          value: 1.75
          resource: research
    - id: aa200001-0001-0001-0001-000000000011
      name: Expanded Archives
      description: Extend the library with additional reading chambers to accommodate more scholars.
      cost:
        gold: 90
        crystals: 40
      effects:
        - type: maxInhabitantBonus
          value: 2
    - id: aa200001-0001-0001-0001-000000000012
      name: Forbidden Knowledge
      description: Unlock the darkest tomes. Greatly boosts research but intensifies the library's fearsome aura.
      cost:
        gold: 120
        crystals: 80
        essence: 30
      effects:
        - type: productionMultiplier
          value: 2.0
          resource: research
        - type: fearIncrease
          value: 2

- id: aa100001-0001-0001-0001-000000000005
  name: Soul Well
  description: A deep well reaching into the spiritual plane, drawing raw essence from departed souls. Its eerie glow and unsettling whispers create a high-fear environment, but the essence it produces is invaluable for dark rituals.
  shapeId: 60e19fcd-7572-4bf0-a626-415be05f6a03
  cost:
    gold: 100
    crystals: 50
  production:
    essence: 0.3
  requiresWorkers: false
  maxInhabitants: 2
  fearLevel: 3
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000003
      bonus: 0.2
      description: Living fungi attract wandering spirits to the well.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000004
      bonus: 0.15
      description: Arcane knowledge from the library focuses the well's spiritual draw.
    - adjacentRoomType: aa100001-0001-0001-0001-000000000005
      bonus: 0.25
      description: Nearby wells create a spiritual resonance that amplifies essence flow.
  upgradePaths:
    - id: aa200001-0001-0001-0001-000000000013
      name: Necrotic Enhancement
      description: Deepen the well's connection to the spirit realm, boosting essence yield and allowing more workers to channel its power.
      cost:
        gold: 120
        crystals: 60
        essence: 25
      effects:
        - type: productionMultiplier
          value: 1.5
          resource: essence
        - type: maxInhabitantBonus
          value: 1
    - id: aa200001-0001-0001-0001-000000000014
      name: Essence Mastery
      description: Purify the well's output for greater efficiency. The refined essence calms the surrounding area, reducing fear.
      cost:
        gold: 100
        crystals: 80
        essence: 40
      effects:
        - type: productionMultiplier
          value: 1.75
          resource: essence
        - type: fearReduction
          value: 1

- id: aa100001-0001-0001-0001-000000000006
  name: Dark Forge
  description: Smelts ores and crafts equipment. Produces gold when worked.
  shapeId: aa000000-0000-0000-0000-000000000003
  cost:
    gold: 60
    crystals: 20
  production:
    gold: 1.2
  requiresWorkers: true
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000002
      bonus: 0.15
      description: Raw crystal ore fuels the forge's smelting process.

- id: aa100001-0001-0001-0001-000000000007
  name: Barracks
  description: Houses and trains your fighters. No resource production.
  shapeId: aa000000-0000-0000-0000-000000000002
  cost:
    gold: 70
  production: {}
  requiresWorkers: false
  adjacencyBonuses: []

- id: aa100001-0001-0001-0001-000000000008
  name: Treasure Vault
  description: A secure chamber for storing gold and valuables. Produces gold passively and boosts the Throne Room when adjacent.
  shapeId: 60e19fcd-7572-4bf0-a626-415be05f6a03
  cost:
    gold: 120
    crystals: 40
  production:
    gold: 0.8
  requiresWorkers: false
  adjacencyBonuses:
    - adjacentRoomType: aa100001-0001-0001-0001-000000000006
      bonus: 0.15
      description: Forged valuables fill the vault more efficiently.
