- id: aa800001-0001-0001-0001-000000000001
  name: Pit Trap
  description: "A concealed pit that causes moderate physical damage and slows invaders."
  effectType: physical
  damage: 15
  duration: 1
  charges: 3
  triggerChance: 0.8
  canBeDisarmed: true
  sprite: trap-pit
  craftCost:
    gold: 30
    crystals: 10

- id: aa800001-0001-0001-0001-000000000002
  name: Arrow Trap
  description: "A wall-mounted mechanism that fires arrows at passing invaders."
  effectType: physical
  damage: 20
  duration: 0
  charges: 5
  triggerChance: 0.7
  canBeDisarmed: true
  sprite: trap-arrow
  craftCost:
    gold: 40
    crystals: 15

- id: aa800001-0001-0001-0001-000000000003
  name: Rune Trap
  description: "A magical rune that deals magic damage bypassing physical defense. Cannot be disarmed."
  effectType: magic
  damage: 25
  duration: 0
  charges: 2
  triggerChance: 0.9
  canBeDisarmed: false
  sprite: trap-rune
  craftCost:
    gold: 50
    essence: 20

- id: aa800001-0001-0001-0001-000000000004
  name: Magic Trap
  description: "An enchantment that reduces the Attack of invaders by 30% for 3 turns."
  effectType: debuff
  damage: 0
  duration: 3
  charges: 4
  triggerChance: 0.75
  canBeDisarmed: true
  sprite: trap-magic
  craftCost:
    gold: 35
    flux: 15

- id: aa800001-0001-0001-0001-000000000005
  name: Fear Glyph
  description: "A terrifying glyph that deals minor damage and demoralizes the invading party."
  effectType: fear
  damage: 8
  duration: 2
  charges: 3
  triggerChance: 0.85
  canBeDisarmed: true
  sprite: trap-fear
  craftCost:
    gold: 25
    essence: 10
