import {
  gameBallGlow,
  gameBurningBlobs,
  gameCrystalGrowth,
  gameExitDoor,
  gameFizzingFlask,
  gameFlowerTwirl,
  gameLeatherBoot,
  gameMeat,
  gameNestedHearts,
  gamePauseButton,
  gamePlayButton,
  gameSpinningSword,
  gameTwoCoins,
  gameVibratingShield,
  gameWarPick,
} from '@ng-icons/game-icons';
import {
  tablerCheck,
  tablerExclamationCircle,
  tablerPlus,
  tablerSettings,
  tablerStar,
  tablerX,
} from '@ng-icons/tabler-icons';

export const ICON_ALL = {
  gameExitDoor,
  gamePauseButton,
  gamePlayButton,
  gameCrystalGrowth,
  gameMeat,
  gameTwoCoins,
  gameFlowerTwirl,
  gameFizzingFlask,
  gameBallGlow,
  gameBurningBlobs,
  gameNestedHearts,
  gameSpinningSword,
  gameVibratingShield,
  gameLeatherBoot,
  gameWarPick,
  tablerPlus,
  tablerSettings,
  tablerStar,
  tablerX,
  tablerCheck,
  tablerExclamationCircle,
};
