- id: 213e57d9-7372-4684-b305-b8786635a660
  name: Goblin
  type: creature
  tier: 1
  description: A scrappy green-skinned worker with a knack for extracting crystals from rock.
  cost:
    gold: 50
    food: 20
  stats:
    hp: 30
    attack: 10
    defense: 8
    speed: 12
    workerEfficiency: 1.0
  traits:
    - id: trait-goblin-miner
      name: Miner
      description: Increases crystal production by 20% when assigned to a crystal-producing room.
      effectType: production_bonus
      effectValue: 0.2
      targetResourceType: crystals
  fearTolerance: 1
  foodConsumptionRate: 2
  stateModifiers:
    scared:
      productionMultiplier: 0.5
      foodConsumptionMultiplier: 1.5
      attackMultiplier: 0.7
      defenseMultiplier: 0.7
    hungry:
      productionMultiplier: 0.5
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.8
      defenseMultiplier: 0.9
    starving:
      productionMultiplier: 0.1
      foodConsumptionMultiplier: 0.5
      attackMultiplier: 0.5
      defenseMultiplier: 0.5
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: 6ecba454-025a-4404-8c0b-ac1f1a0b4779
  name: Kobold
  type: creature
  tier: 1
  description: A swift, cunning reptilian that excels at setting traps for intruders.
  cost:
    gold: 40
    food: 15
  stats:
    hp: 20
    attack: 8
    defense: 5
    speed: 18
    workerEfficiency: 0.9
  traits:
    - id: trait-kobold-trapper
      name: Trapper
      description: Skilled at laying traps that slow and damage invaders.
      effectType: trap_bonus
      effectValue: 0.25
  fearTolerance: 2
  foodConsumptionRate: 1.5
  stateModifiers:
    scared:
      productionMultiplier: 1.1
      foodConsumptionMultiplier: 2.0
      attackMultiplier: 1.2
      defenseMultiplier: 0.8
    hungry:
      productionMultiplier: 0.7
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.9
      defenseMultiplier: 0.9
    starving:
      productionMultiplier: 0.1
      foodConsumptionMultiplier: 0.5
      attackMultiplier: 0.5
      defenseMultiplier: 0.5
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: c970d8c0-e920-4844-95ff-362f971abf06
  name: Skeleton
  type: undead
  tier: 1
  description: A tireless undead guardian that never needs food or rest.
  cost:
    gold: 60
    essence: 15
  stats:
    hp: 40
    attack: 12
    defense: 15
    speed: 6
    workerEfficiency: 0.7
  traits:
    - id: trait-skeleton-guardian
      name: Guardian
      description: Increases room defense effectiveness against invaders.
      effectType: defense_bonus
      effectValue: 0.3
  fearTolerance: 4
  foodConsumptionRate: 0
  stateModifiers:
    scared:
      productionMultiplier: 0.9
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.9
      defenseMultiplier: 0.95
    hungry:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0
    starving:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: 0a597510-e8c7-4aab-ad71-43ce6f51ad50
  name: Myconid
  type: fungal
  tier: 1
  description: A sentient mushroom creature that thrives in dark, damp environments.
  cost:
    gold: 45
    food: 25
  stats:
    hp: 25
    attack: 5
    defense: 10
    speed: 8
    workerEfficiency: 1.3
  traits:
    - id: trait-myconid-farmer
      name: Farmer
      description: Increases food production by 15% when assigned to a food-producing room.
      effectType: production_bonus
      effectValue: 0.15
      targetResourceType: food
  fearTolerance: 1
  foodConsumptionRate: 1
  stateModifiers:
    scared:
      productionMultiplier: 0.3
      foodConsumptionMultiplier: 1.5
      attackMultiplier: 0.5
      defenseMultiplier: 0.6
    hungry:
      productionMultiplier: 0.6
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.7
      defenseMultiplier: 0.8
    starving:
      productionMultiplier: 0.1
      foodConsumptionMultiplier: 0.5
      attackMultiplier: 0.3
      defenseMultiplier: 0.4
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: d336e6e7-2d96-41cb-af02-106b34efbc16
  name: Slime
  type: ooze
  tier: 1
  description: A cheap, adaptable blob that can fill any role poorly but costs almost nothing to recruit.
  cost:
    gold: 15
  stats:
    hp: 15
    attack: 3
    defense: 3
    speed: 5
    workerEfficiency: 0.6
  traits:
    - id: trait-slime-adaptable
      name: Adaptable
      description: Can be assigned to any room type without penalty.
      effectType: versatility
      effectValue: 1.0
  fearTolerance: 0
  foodConsumptionRate: 0.5
  stateModifiers:
    scared:
      productionMultiplier: 0.4
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.5
      defenseMultiplier: 0.5
    hungry:
      productionMultiplier: 0.8
      foodConsumptionMultiplier: 1.0
    starving:
      productionMultiplier: 0.1
      foodConsumptionMultiplier: 0.5
      attackMultiplier: 0.2
      defenseMultiplier: 0.2
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: 86d7ac62-3300-4d3c-9bc4-d5d12ee9d845
  name: Dragon
  type: dragon
  tier: 4
  description: An ancient wyrm of immense power. Its presence inspires ferocity in all dungeon defenders.
  cost:
    gold: 500
    essence: 200
    crystals: 100
  stats:
    hp: 500
    attack: 80
    defense: 60
    speed: 20
    workerEfficiency: 1.0
  traits: []
  restrictionTags:
    - unique
  rulerBonuses:
    attack: 0.10
    fear: 0.05
  rulerFearLevel: 4
  fearTolerance: 4
  foodConsumptionRate: 5
  stateModifiers:
    scared:
      productionMultiplier: 0.9
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.95
      defenseMultiplier: 0.95
    hungry:
      productionMultiplier: 0.8
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.9
      defenseMultiplier: 0.9
    starving:
      productionMultiplier: 0.1
      foodConsumptionMultiplier: 0.5
      attackMultiplier: 0.6
      defenseMultiplier: 0.6
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: 8339f820-cd95-415f-ad76-fbdafe974800
  name: Lich
  type: undead
  tier: 4
  description: A master of dark arcana who has transcended death itself. Its intellect accelerates all research and flux generation.
  cost:
    gold: 400
    essence: 300
    crystals: 50
  stats:
    hp: 300
    attack: 40
    defense: 30
    speed: 15
    workerEfficiency: 1.0
  traits: []
  restrictionTags:
    - unique
  rulerBonuses:
    researchSpeed: 0.20
    fluxProduction: 0.15
  rulerFearLevel: 3
  fearTolerance: 4
  foodConsumptionRate: 0
  stateModifiers:
    scared:
      productionMultiplier: 0.95
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.9
      defenseMultiplier: 0.9
    hungry:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0
    starving:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0

- id: 29912034-2c86-498a-a666-0daa617f400c
  name: Demon Lord
  type: demon
  tier: 4
  description: A terrifying lord of the abyss. Its malevolent aura corrupts everything and crushes the will of invaders.
  cost:
    gold: 450
    essence: 150
    corruption: 100
  stats:
    hp: 400
    attack: 70
    defense: 50
    speed: 25
    workerEfficiency: 1.0
  traits: []
  restrictionTags:
    - unique
  rulerBonuses:
    corruptionGeneration: 0.25
    fear: 0.10
    invaderMorale: -0.10
  rulerFearLevel: 5
  fearTolerance: 4
  foodConsumptionRate: 3
  stateModifiers:
    scared:
      productionMultiplier: 0.95
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.95
      defenseMultiplier: 0.95
    hungry:
      productionMultiplier: 0.9
      foodConsumptionMultiplier: 1.0
      attackMultiplier: 0.95
      defenseMultiplier: 0.95
    starving:
      productionMultiplier: 0.1
      foodConsumptionMultiplier: 0.5
      attackMultiplier: 0.6
      defenseMultiplier: 0.6
    normal:
      productionMultiplier: 1.0
      foodConsumptionMultiplier: 1.0
