# Warrior - High HP/Attack, defensive tank
- id: fce64c3f-f9bc-4a8e-bfa6-2760d8d6d14e
  name: Warrior
  description: A heavily armored fighter with high HP and strong attacks. Uses Shield Wall to reduce incoming damage.
  invaderClass: warrior
  baseStats:
    hp: 30
    attack: 8
    defense: 7
    speed: 3
  combatAbilityIds:
    - Shield Wall
  sprite: invader-warrior

# Rogue - High Speed, trap specialist
- id: 3290cd7b-9c5d-4671-8848-91626bd5bc05
  name: Rogue
  description: A swift and cunning infiltrator. Can disarm traps and deal devastating backstab damage.
  invaderClass: rogue
  baseStats:
    hp: 15
    attack: 6
    defense: 3
    speed: 10
  combatAbilityIds:
    - Disarm Trap
    - Backstab
  sprite: invader-rogue

# Mage - High magic Attack, spell-focused
- id: d3bc3506-4c94-44ea-9974-7a4edb444b17
  name: Mage
  description: A powerful spellcaster whose arcane bolts ignore physical defenses. Can dispel magical protections.
  invaderClass: mage
  baseStats:
    hp: 12
    attack: 10
    defense: 2
    speed: 5
  combatAbilityIds:
    - Arcane Bolt
    - Dispel
  sprite: invader-mage

# Cleric - High Defense, healer and anti-undead
- id: 6b6210c0-f924-4d79-87fd-17af1517e298
  name: Cleric
  description: A holy warrior who heals allies and deals devastating damage to undead creatures.
  invaderClass: cleric
  baseStats:
    hp: 20
    attack: 4
    defense: 8
    speed: 4
  combatAbilityIds:
    - Heal
    - Turn Undead
  sprite: invader-cleric

# Paladin - High HP/Defense, anti-corruption champion
- id: 3d860aec-eda7-4170-b62f-364e6144ce0b
  name: Paladin
  description: A righteous champion who smites corrupted foes and inspires courage in allies against fear.
  invaderClass: paladin
  baseStats:
    hp: 28
    attack: 7
    defense: 9
    speed: 2
  combatAbilityIds:
    - Smite Evil
    - Aura of Courage
  sprite: invader-paladin

# Ranger - High Speed, scout and marker
- id: b1b8c630-39fb-4b2f-bf3c-990c657fc96c
  name: Ranger
  description: A skilled tracker who scouts ahead and marks targets, increasing all damage against them.
  invaderClass: ranger
  baseStats:
    hp: 18
    attack: 7
    defense: 4
    speed: 9
  combatAbilityIds:
    - Scout
    - Mark Target
  sprite: invader-ranger
