- id: ca000001-0000-4000-a000-000000000001
  name: Breath Weapon
  description: AOE fire damage
  effectType: Damage
  value: 150
  chance: 100
  cooldown: 3
  targetType: aoe
  duration: 0

- id: ca000001-0000-4000-a000-000000000002
  name: Petrifying Gaze
  description: Stuns a single target
  effectType: Stun
  value: 0
  chance: 10
  cooldown: 0
  targetType: single
  duration: 3

- id: ca000001-0000-4000-a000-000000000003
  name: Death Bolt
  description: Single target 200% magic damage
  effectType: Damage
  value: 200
  chance: 100
  cooldown: 2
  targetType: single
  duration: 0

- id: ca000001-0000-4000-a000-000000000004
  name: Wraith Evasion
  description: 50% chance to evade physical attacks
  effectType: Evasion
  value: 0
  chance: 50
  cooldown: 0
  targetType: self
  duration: 0

- id: ca000001-0000-4000-a000-000000000005
  name: Berserk Rage
  description: +100% attack when below 50% HP
  effectType: Buff Attack
  value: 100
  chance: 50
  cooldown: 0
  targetType: self
  duration: 0

- id: ca000001-0000-4000-a000-000000000006
  name: Lich Shield
  description: +50% defense for 3 turns
  effectType: Buff Defense
  value: 50
  chance: 100
  cooldown: 4
  targetType: self
  duration: 3

# --- Invader combat abilities ---

# Warrior abilities
- id: ca000001-0000-4000-a000-000000000007
  name: Shield Wall
  description: Reduces incoming damage by 25% for 2 turns
  effectType: Buff Defense
  value: 25
  chance: 100
  cooldown: 4
  targetType: self
  duration: 2

# Rogue abilities
- id: ca000001-0000-4000-a000-000000000008
  name: Disarm Trap
  description: 60% chance to disarm a trap before triggering
  effectType: Disarm
  value: 60
  chance: 100
  cooldown: 0
  targetType: single
  duration: 0

- id: ca000001-0000-4000-a000-000000000009
  name: Backstab
  description: Deals double damage to a single target
  effectType: Damage
  value: 200
  chance: 100
  cooldown: 3
  targetType: single
  duration: 0

# Mage abilities
- id: ca000001-0000-4000-a000-000000000010
  name: Arcane Bolt
  description: Magical attack that ignores physical defense
  effectType: Magic Damage
  value: 150
  chance: 100
  cooldown: 2
  targetType: single
  duration: 0

- id: ca000001-0000-4000-a000-000000000011
  name: Dispel
  description: Removes all active buffs from a target
  effectType: Dispel
  value: 0
  chance: 100
  cooldown: 3
  targetType: single
  duration: 0

# Cleric abilities
- id: ca000001-0000-4000-a000-000000000012
  name: Heal
  description: Restores 20% of max HP to a single target
  effectType: Heal
  value: 20
  chance: 100
  cooldown: 3
  targetType: single
  duration: 0

- id: ca000001-0000-4000-a000-000000000013
  name: Turn Undead
  description: Deals 150% bonus damage to undead creatures
  effectType: Damage
  value: 150
  chance: 100
  cooldown: 2
  targetType: aoe
  duration: 0

# Paladin abilities
- id: ca000001-0000-4000-a000-000000000014
  name: Smite Evil
  description: Deals 200% bonus damage to corrupted targets
  effectType: Damage
  value: 200
  chance: 100
  cooldown: 2
  targetType: single
  duration: 0

- id: ca000001-0000-4000-a000-000000000015
  name: Aura of Courage
  description: Grants fear immunity to all nearby allies
  effectType: Fear Immunity
  value: 0
  chance: 100
  cooldown: 0
  targetType: aoe
  duration: 0

# Ranger abilities
- id: ca000001-0000-4000-a000-000000000016
  name: Scout
  description: Reveals 2 rooms ahead on the invasion path
  effectType: Scout
  value: 2
  chance: 100
  cooldown: 0
  targetType: self
  duration: 0

- id: ca000001-0000-4000-a000-000000000017
  name: Mark Target
  description: Marks a target for +20% damage for 3 turns
  effectType: Mark
  value: 20
  chance: 100
  cooldown: 0
  targetType: single
  duration: 3
