- id: cedc340b-2f75-4811-89e5-b971659950fc
  name: Square 2x2
  width: 2
  height: 2
  tiles:
    - { x: 0, y: 0 }
    - { x: 1, y: 0 }
    - { x: 0, y: 1 }
    - { x: 1, y: 1 }

- id: 36a2e61f-079d-422b-bd6a-1eb5b105e794
  name: Square 3x3
  width: 3
  height: 3
  tiles:
    - { x: 0, y: 0 }
    - { x: 1, y: 0 }
    - { x: 2, y: 0 }
    - { x: 0, y: 1 }
    - { x: 1, y: 1 }
    - { x: 2, y: 1 }
    - { x: 0, y: 2 }
    - { x: 1, y: 2 }
    - { x: 2, y: 2 }

- id: d487da0e-8fa6-4a13-b0bf-da3e87c8d52f
  name: Square 4x4
  width: 4
  height: 4
  tiles:
    - { x: 0, y: 0 }
    - { x: 1, y: 0 }
    - { x: 2, y: 0 }
    - { x: 3, y: 0 }
    - { x: 0, y: 1 }
    - { x: 1, y: 1 }
    - { x: 2, y: 1 }
    - { x: 3, y: 1 }
    - { x: 0, y: 2 }
    - { x: 1, y: 2 }
    - { x: 2, y: 2 }
    - { x: 3, y: 2 }
    - { x: 0, y: 3 }
    - { x: 1, y: 3 }
    - { x: 2, y: 3 }
    - { x: 3, y: 3 }

- id: 82f509dd-9ff8-4c99-986d-0b57198a4749
  name: L-Shape
  width: 3
  height: 3
  tiles:
    - { x: 0, y: 0 }
    - { x: 0, y: 1 }
    - { x: 0, y: 2 }
    - { x: 1, y: 2 }
    - { x: 2, y: 2 }

- id: d422fcc4-ecb1-4be0-8103-a39773440dc9
  name: T-Shape
  width: 3
  height: 2
  tiles:
    - { x: 0, y: 0 }
    - { x: 1, y: 0 }
    - { x: 2, y: 0 }
    - { x: 1, y: 1 }

- id: ac447f9c-de8c-4b07-8756-b0b570845ace
  name: I-Shape
  width: 1
  height: 4
  tiles:
    - { x: 0, y: 0 }
    - { x: 0, y: 1 }
    - { x: 0, y: 2 }
    - { x: 0, y: 3 }

- id: 1c224b76-8f8c-4795-a25c-eac11a1acc20
  name: Small L-Shape
  width: 2
  height: 3
  tiles:
    - { x: 1, y: 0 }
    - { x: 1, y: 1 }
    - { x: 0, y: 2 }
    - { x: 1, y: 2 }

- id: a3f7c2e1-9b4d-4e8a-b6c5-d0f1e2a3b4c5
  name: U-Shape
  width: 3
  height: 3
  tiles:
    - { x: 0, y: 0 }
    - { x: 2, y: 0 }
    - { x: 0, y: 1 }
    - { x: 2, y: 1 }
    - { x: 0, y: 2 }
    - { x: 1, y: 2 }
    - { x: 2, y: 2 }
