# Research nodes define the tech tree for dungeon advancement.
# Three branches: dark, arcane, engineering
# Each node has: id, name, description, branch, cost, prerequisiteResearchIds, unlocks, tier, requiredTicks
# Unlock effect types: room, inhabitant, ability, upgrade, passive_bonus

# --- DARK BRANCH: root node ---
- id: 965efdaa-6c12-48e3-8337-3ad70b5d309d
  name: Dark Arts Fundamentals
  description: The foundational study of dark magic, opening paths to necromancy and soul manipulation.
  branch: dark
  cost:
    research: 10
  prerequisiteResearchIds: []
  unlocks:
    - type: room
      targetId: 8508ed7f-61d0-40b1-aacd-116b7be96d5a
  tier: 1
  requiredTicks: 50

# --- ARCANE BRANCH: root node ---
- id: dd7790ca-f564-422d-80bf-932870898d70
  name: Arcane Basics
  description: Introduction to the fundamental principles of arcane magic and flux manipulation.
  branch: arcane
  cost:
    research: 10
  prerequisiteResearchIds: []
  unlocks:
    - type: room
      targetId: 89e5e8a8-2ceb-45f5-b2d5-21ded39ceb26
  tier: 1
  requiredTicks: 50

# --- ENGINEERING BRANCH: root node ---
- id: 25f6d6de-5850-44eb-8e98-c2b882791d4c
  name: Basic Engineering
  description: Foundational construction techniques for building stronger dungeon structures.
  branch: engineering
  cost:
    research: 10
  prerequisiteResearchIds: []
  unlocks:
    - type: room
      targetId: ae673803-b514-4da9-a0d4-df448aa412a4
    - type: room
      targetId: dcecac50-d80f-4ca9-b004-7a2cb0876ed0
  tier: 1
  requiredTicks: 50
