# Research nodes define the tech tree for dungeon advancement.
# Three branches: dark, arcane, engineering
# Each node has: id, name, description, branch, cost, prerequisiteResearchIds, unlocks, tier, requiredTicks
# Unlock effect types: room, inhabitant, ability, upgrade, passive_bonus

# --- DARK BRANCH: root node ---
- id: 965efdaa-6c12-48e3-8337-3ad70b5d309d
  name: Dark Arts Fundamentals
  description: The foundational study of dark magic, opening paths to necromancy and soul manipulation.
  branch: dark
  cost:
    research: 10
  prerequisiteResearchIds: []
  unlocks:
    - type: room
      targetRoomId: Soul Well
  tier: 1
  requiredTicks: 50

# --- ARCANE BRANCH: root node ---
- id: dd7790ca-f564-422d-80bf-932870898d70
  name: Arcane Basics
  description: Introduction to the fundamental principles of arcane magic and flux manipulation.
  branch: arcane
  cost:
    crystals: 10
  prerequisiteResearchIds: []
  unlocks:
    - type: room
      targetRoomId: Shadow Library
  tier: 1
  requiredTicks: 50

# --- ENGINEERING BRANCH: root node ---
- id: 25f6d6de-5850-44eb-8e98-c2b882791d4c
  name: Basic Engineering
  description: Foundational construction techniques for building stronger dungeon structures.
  branch: engineering
  cost:
    research: 10
  prerequisiteResearchIds: []
  unlocks:
    - type: room
      targetRoomId: Dark Forge
    - type: room
      targetRoomId: Barracks
  tier: 1
  requiredTicks: 50
