- id: d24ea771-7bc8-4157-809e-31f97241e73c
  name: Crystal
  resourceType: crystals
  defaultMax: 500

- id: 4d01d142-09f2-4586-9441-81962409bae5
  name: Food
  resourceType: food
  defaultMax: 500

- id: ac38d42e-897c-4a27-bd84-6e25463058a7
  name: Gold
  resourceType: gold
  defaultMax: 1000

- id: 27ae39e1-d365-41bd-a46d-c1e994aaa27c
  name: Flux
  resourceType: flux
  defaultMax: 200

- id: 0813a67a-d03f-4d3f-bf68-70d2cfaca8ab
  name: Research
  resourceType: research
  defaultMax: 300

- id: 3f2be4c4-803c-4b0d-91f0-0ebea0eb914c
  name: Essence
  resourceType: essence
  defaultMax: 200

- id: f1c87151-aea3-436b-a81d-347fdd706a27
  name: Corruption
  resourceType: corruption
  defaultMax: 100
